version: '3.9'



services:
  postgres1:
    image: postgres:13.3
    environment:
      DATABASE_URL: "jdbc:postgresql://localhost:5432/postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"


  messenger:
    build: ./messenger
    container_name: messenger
    restart: always
    ports:
      - "8080:8080"
